apiVersion: v1
kind: Service
metadata:
  name:  paramaah-rtp-service
  namespace: paramaah
spec:
  type: NodePort
  selector:
    app: paramaah-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
